### ISSUE TITLE
Event Handler Bug

### ISSUE THREAD

**Issue by akanora** [TheArmagan/basit-altyapi#1]
Event handler üzerinde bulunan bir hatadan dolayı `guildDelete` gibi şeyler kullanılamıyor. Bilgiler kullanılamadan siliniyor hatta event direkt çalışmıyor. Aksine `GuildCreate` çalışıyor.

**Comment by TheArmagan** [comment]
Sorun son göncelleme ile çözüldü sadece index.js dosyasını güncellemeniz yeterlidir.
