### ISSUE TITLE
Hata Raporu

### ISSUE THREAD

**Issue by Ruqen** [TheArmagan/basit-altyapi#12]
**Hatayı Açıklayın**
Tamamen temiz ve basit kurulumun ardından çalıştırınca 'DISALLOWED_INTENTS' hatasını atıyor.

**Hatayı Yeniden Üretmek İçin**
Şunları yaparak bu sorunu yeniden oluşturabilirsiniz:
- Botu release kısmından indir
- Tokenini gir
- node index.js

**Normalde Olması Gereken**
Hatasız bir şekilde çalışmalı

**Ekran Fotoğrafları**
https://prnt.sc/1ynz5jr

**Sistem Bilgileri:**
 - İşletim Sisteminiz (orn. Windowns, Linux): Windows
 - İşletim Sisteminizin Versiyionu (orn. 19043.1110): 20H2 19042.1288
 - Node.JS Versiyonunuz (orn. v16.4.1): v16.13.0
 - basit-altyapi Versiyonunuz (orn: main-1.4.8): v1.9.1

**Comment by Ruqen** [comment]
UPDATE: Developer portal'dan bu özellikleri açmanız gerekiyor. Bunu dokümantasyona eklemen faydalı olabilir. ^^

![image](https://user-images.githubusercontent.com/73693641/140656385-7bae0f82-7a8f-492c-9e0e-205eddabac3c.png)

**Comment by TheArmagan** [comment]
Bu sorun sizin tarafınızca bakılması gerekn bir sorun. Ancak biz bir uyarı mesajı ekleyebiliriz.
